### ISSUE TITLE
Broad Arm architecture support

### ISSUE THREAD

**Issue by GeorgeHahn** [CraneStation/target-lexicon#11]
There are many ([many many..](https://github.com/gcc-mirror/gcc/blob/d83eca59fee00f833f4bbb62fb5460a562a64c0c/gcc/config/arm/arm-cpus.in#L261)) different Arm architectures. It would be great to be able to parse all of these into something meaningful.

What do you think would be a good solution for this? I'm happy to add all `arch` entries from the above list, but that would significantly increase downstream code to handle Arm triples. This could pair well with a broad 'architecture family' mapping (#9), but perhaps there is a better solution.

An `Arm` struct containing architecture information like ISA variant and available features (NEON, FPU, etc) may be broadly useful. This should additionally fulfill the request in #9 by allowing for matching to architectures at varying levels of granularity.

For context, this is in relation to https://github.com/alexcrichton/cc-rs/issues/390 where I suggest that the `cc` crate take a dependency on this crate for triple handling.

**Comment by sunfishcode** [comment]
Another possible approach here is to add family-specific enums, such as an `ARMArchitecture` enum:

```rust
pub enum ARMArchitecture {
    Armv4t,
    Armv5te,
    Armv6,
    Armv7,
    Armv7r,
    Armv7s,
    ...
}
```

and then have `Architecture` use that instead of having all the variants at the top level:

pub enum Architecture {
    ...
    Arm(ARMArchitecture),
    ...
}
```

Then the ARM-specific feature predicates could go in an `impl ARMArchitecture`. Would you be interested in factoring out target-lexicon's ARM architectures in this way?

**Comment by GeorgeHahn** [comment]
That makes a lot of sense, I like it! I'd be very interested in implementing this.
