### ISSUE TITLE
Make `host` a const function

### ISSUE THREAD

**Issue by jyn514** [CraneStation/target-lexicon#18]
Current behavior:

```rust
$ cat src/main.rs
use target_lexicon::Triple;

const HOST: Triple = Triple::host();

fn main() {
    println!("{}", HOST.pointer_width().unwrap().bytes());
}
$ cargo run
error[E0015]: calls in constants are limited to constant functions, tuple structs and tuple variants
 --> src/main.rs:3:22
  |
3 | const HOST: Triple = Triple::host();
```

Expected behavior:
```
$ cargo run
8
```

Looking at [the implementation of `host`](https://docs.rs/target-lexicon/0.4.0/x86_64-unknown-linux-gnu/src/target_lexicon/home/cratesfyi/cratesfyi/x86_64-unknown-linux-gnu/debug/build/target-lexicon-ec0f3fd42f942f61/out/host.rs.html#47-55), it's just a struct with some enum variants, so there shouldn't be too much trouble making it const.

I'm happy to make a pull request if the change is welcome.

**Comment by sunfishcode** [comment]
Fixed in #19
