### ISSUE TITLE
This crate could be drastically simplified

### ISSUE THREAD

**Issue by nox** [CraneStation/target-lexicon#30]
So first, I'm convinced now that `TARGET` in a build script never points to a JSON file path.

Cargo does accept JSON file paths in its `--target` flag, as shown here:

https://github.com/rust-lang/cargo/blob/759431fe98c5e21546ef587945eb0a78cb60f331/src/cargo/core/compiler/compile_kind.rs#L54-L70

But it never passes it to build scripts as is, as shown here:

https://github.com/rust-lang/cargo/blob/759431fe98c5e21546ef587945eb0a78cb60f331/src/cargo/core/compiler/custom_build.rs#L161

Because the `short_name` method does take the triple from the JSON config if the `--target` value was a JSON file path:

https://github.com/rust-lang/cargo/blob/759431fe98c5e21546ef587945eb0a78cb60f331/src/cargo/core/compiler/compile_kind.rs#L110-L127

Second, I'm pretty sure that everything this crate extracts from said JSON file path is actually already available to the environment of the build script and has no business being extracted from a different source. Here is what is populated by Cargo in the build script environment:

```
("CARGO_CFG_TARGET_ARCH", "x86_64")
("CARGO_CFG_TARGET_ENDIAN", "little")
("CARGO_CFG_TARGET_ENV", "")
("CARGO_CFG_TARGET_FAMILY", "unix")
("CARGO_CFG_TARGET_FEATURE", "fxsr,sse,sse2,sse3,ssse3")
("CARGO_CFG_TARGET_OS", "macos")
("CARGO_CFG_TARGET_POINTER_WIDTH", "64")
("CARGO_CFG_TARGET_VENDOR", "apple")
```

So the entire crate, AFAICT, can be reimplemented to use that instead.

Cc @bnjbvr who wanted to remove the `serde_json` dependency altogether.

**Comment by bnjbvr** [comment]
Thanks for filing an issue. If the build script doesn't support the custom target JSON value, we could rip a lot of code out indeed.

cc @sunfishcode @lachlansneff

**Comment by sunfishcode** [comment]
I don't remember the reason why JSON support was needed in target-lexicon; @lachlansneff do you remember?

The `CARGO_CFG_TARGET_*` and friends don't match up exactly with the actual triple fields; rustc does its own custom normalization. For vendor, there's "unknown" vs "none", for environment, there's "musl" vs "musleabi", for arch, there's "thumbv7em" etc. vs "arm", for os, there's "linux" vs "android". target-lexicon wants to know the actual triple, not rustc's normalized version of it.

Also, target-lexicon aims to be usable outside of cargo and rustc, so even if those environment variables could be relied on, they wouldn't obsolete the rest of the crate :-).

**Comment by nox** [comment]
> The `CARGO_CFG_TARGET_*` and friends don't match up exactly with the actual triple fields; rustc does its own custom normalization. For vendor, there's "unknown" vs "none", for environment, there's "musl" vs "musleabi", for arch, there's "thumbv7em" etc. vs "arm", for os, there's "linux" vs "android". target-lexicon wants to know the actual triple, not rustc's normalized version of it.

Don't forget that `TARGET` contains the actual triple.

> Also, target-lexicon aims to be usable outside of cargo and rustc, so even if those environment variables could be relied on, they wouldn't obsolete the rest of the crate :-).

I meant that this crate can use the environment to emit whatever it wants to emit, without relying on a JSON parser.

**Comment by lachlansneff** [comment]
@sunfishcode Hmm, I can't remember why we added target config parsing. I seem to remember that it was necessary, but perhaps that was not true.

**Comment by sunfishcode** [comment]
In that case, it seems to make sense to remove the JSON parsing altogether, at least until we find an actual use case that needs it. Anyone interested in submitting a PR for this? :smile:
