### ISSUE TITLE
Fails to build with target thumbv7neon-linux-androideabi

### ISSUE THREAD

**Issue by glandium** [CraneStation/target-lexicon#7]
```
error: failed to run custom build command for `target-lexicon v0.2.0 (/tmp/target-lexicon)`
process didn't exit successfully: `/tmp/target-lexicon/target/debug/build/target-lexicon-b09bc95d372d7e69/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'can't find custom target thumbv7neon-linux-androideabi', build.rs:99:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by glandium** [comment]
In fact, it fails for any (new) target that is not listed in src/targets.rs.

**Comment by glandium** [comment]
It feels like src/targets.rs should be build-time-generated from the output of `rustc --print target-list`.

**Comment by bnjbvr** [comment]
> It feels like src/targets.rs should be build-time-generated from the output of rustc --print target-list.

It's strange that the fallback path that searches for json target descriptors in the `RUST_TARGET_PATH` directory didn't work. That being said, if it didn't work, how could we figure out endianness / pointer width by looking at the output of `rustc --print target-list`? Now trying to see if rustc provides this information somewhere in a different command, or where it looks to find it.

**Comment by bnjbvr** [comment]
So rustc has access to all this information, for instance for [your target](https://github.com/rust-lang/rust/blob/master/src/librustc_target/spec/thumbv7neon_linux_androideabi.rs). There's also a [function](https://github.com/rust-lang/rust/blob/master/src/librustc_target/spec/mod.rs#L1178) that returns a Target from the string, as this crate does, with the same `RUST_TARGET_PATH` dance. 

`rustc --print cfg` or `rustc +nightly --print target-spec-json -Z unstable-options` only print the options for the current target. Rustc could be improved so we can request the target description for any target (not only the current one) and then we could use this. Or `librustc_target` could be a build dependency of this crate and then we could use the `search` function (but that sounds a bit overwhelming for this use case).

**Comment by bnjbvr** [comment]
Actually, we can just do `rustc --print cfg --target $TARGET_NAME` and get this information, so there might be a way.

**Comment by sunfishcode** [comment]
I'm a little nervous about auto-generating the target list, as triple parsing involves several special cases, and they change over time. I've now updated the target list to the full list from Rust 1.33, and for example, x86_64-unknown-fuchsia arbitrarily changed to x86_64-fuchsia, requiring new special-case logic. As another, we now have triples like riscv32imc-unknown-none-elf, which include the "unknown" vendor, which broke the the old special-case rule to omit the "unknown" vendor for triples like thumbv6m-none-eabi. We now have a new special-case rule, which handles the new set of known triples, but I expect we'll need more changes in the future.

Also, the sets of known architectures and other things are part of the API, and it's easier on downstream packages if target-lexicon's API doesn't change depending on what version and configuration of rustc it's compiled with. So while I acknowledge that it's inconvenient that these things aren't auto-updated, for now it seems best to continue to manually update them.
